#홈페이지에서 API서비스 신청시 받은 Appkey, Appsecret 값 설정
# 위탁형2(정찬희)
APP_KEY: "PSaFZXv2NcQ4oorFK9p9HmJVMrjJKEIiSNe3"
APP_SECRET: "8eGJaW+91vH5PQkLf9G7fNiK1Kn8wBuwjB+QRSJCPaRK5Y3JktUj6T4wFgQ/gAGRvpEmQae+vJXIt3cw3VgNqWEOuVUD5YhgoerVVeeKlL24FRPjn8aE3lzJS10aTxWRMA83ul3U7GahQqGOBJRo6W3iIVjG19GtIHK0gW/JrUykp1GIh/0="

# #계좌번호 앞 8자리(정찬희)
CANO: "64552083"
ACNT_PRDT_CD: "01"
PASSWORD: "rotc1994!"

#실전투자
URL_BASE: "https://openapi.koreainvestment.com:9443"

#디스코드 웹훅 URL(한국투자증권 - 변동성돌파매매, 주도주)
DISCORD_WEBHOOK_URL: "https://discordapp.com/api/webhooks/1280133788835250339/twz2SnipW6lU3XQzOgYW7QJ8vYSYhVjuctOaS_b8wGGDQGi7rtPtpQoS81TVWekdrfLk"

DISCORD_WEBHOOK_URL2: "https://discordapp.com/api/webhooks/1292438024998883400/m-gDAnW70Css68u_xLmhPZh0zqfRJKahjLEwFZqpCpIV34tQU6aG9FIiqvsetCNOx0HI"
