# #위탁형(맹미숙)
# APP_KEY: "PSmUD00zXsRH4873h0Ip7Tj0DqkMkv0fd7PW"
# APP_SECRET: "VndBDldr9LXslKFsADcTib2Xt5aqT+coGO1ZKuNhVDc26EKYGpLMoe2y/bT0tSWf3/hEVu8/7j7XUvKj/pUGmy4ZO6bPc2XC5hEXgjXL88tZqyPjeyflGclmhTRqqJXWcUWR96K3rdmTW+reLKvAIf+yJL3BIvBDDFS7UBTnGu75cYECsrI="

# #계좌번호 앞 8자리(맹미숙)
# CANO: "64422438"
# ACNT_PRDT_CD: "01"
# #===================================================

# #실전투자
# URL_BASE: "https://openapi.koreainvestment.com:9443"

#디스코드 웹훅 URL 
DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1459456714490249388/00FgddcstkBrmQzAanSYrA4n0wh33-YBiQm9K6S4ZYe2srFmslhSb4573iQXB-aDNQyq"