#홈페이지에서 API서비스 신청시 받은 Appkey, Appsecret 값 설정

#위탁형(정찬희)
APP_KEY: "PSJtVENV6catpuZ6uRxElrHsgVb5FHXYShip"
APP_SECRET: "+4QElnAj1AD9v0/SkxIMboN6y3PkSXUPih2HKL5cpjl/ZMV0CdawYVrzhCMXh1B1Tnxiz8PG1Zxby6lWxK1BXoF3sUuM1xz469qT7ekdF8zTnAXDJ3de7xl92QW4YWAJPcEwgyYib+P4Zs4JpkFvkXlxH1X8iJ5gNVyHvLFOrR6xXJ38DzI="

#계좌번호 앞 8자리(정찬희)
CANO: "64470842"
#계좌번호 뒤 2자리
ACNT_PRDT_CD: "01"
# MySql DB PASSWORD
PASSWORD: "rotc1994!"

#===================================================
#위탁형(맹미숙)
#APP_KEY: "PSmUD00zXsRH4873h0Ip7Tj0DqkMkv0fd7PW"
#APP_SECRET: "VndBDldr9LXslKFsADcTib2Xt5aqT+coGO1ZKuNhVDc26EKYGpLMoe2y/bT0tSWf3/hEVu8/7j7XUvKj/pUGmy4ZO6bPc2XC5hEXgjXL88tZqyPjeyflGclmhTRqqJXWcUWR96K3rdmTW+reLKvAIf+yJL3BIvBDDFS7UBTnGu75cYECsrI="

#계좌번호 앞 8자리(맹미숙)
#CANO: "64422438"
#계좌번호 뒤 2자리
#ACNT_PRDT_CD: "01"
#===================================================

#실전투자
URL_BASE: "https://openapi.koreainvestment.com:9443"
#모의투자
# URL_BASE: "https://openapivts.koreainvestment.com:29443"

#디스코드 웹훅 URL
DISCORD_WEBHOOK_URL: "https://discordapp.com/api/webhooks/1300432958707994725/_DCdTgXVPSxgf_MnlVInvC7GvDIanEilzw1hjJenANv2FaA4aZUY0IoPNdtiPjBxxdkk"

DISCORD_WEBHOOK_URL2: "https://discordapp.com/api/webhooks/1292438024998883400/m-gDAnW70Css68u_xLmhPZh0zqfRJKahjLEwFZqpCpIV34tQU6aG9FIiqvsetCNOx0HI"